---

# Run the command
# ansible-galaxy install -r requirements.yml
# to install Ansible Galaxy Roles

- src: geerlingguy.repo-epel
- src: geerlingguy.java
- src: geerlingguy.nginx
- src: geerlingguy.elasticsearch
- src: geerlingguy.elasticsearch-curator
- src: geerlingguy.kibana
- src: geerlingguy.logstash
- src: geerlingguy.logstash-forwarder


